frontend:
  image:
    repository: "<docker image link>"
    # repository: nginx
    tag: "<docker image tag>"
    pullPolicy: IfNotPresent

  replicaCount: 2

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    host: ""

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}

backend:
  replicaCount: 2

  image:
    repository: "<docker image link>"
    tag: "<docker image tag>"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000

  env:
    DB_USER: "<db_user DB_NAME>"
    DB_PASSWORD: "<db password>"
    DB_HOST: "<DB IP>"
    DB_PORT: "<port num - 5432 def>"
    DB_NAME: "<DB_NAME>"
    API_TOKEN: "mysecrettoken123"